Repository hicks-team/RecipeBook, pull requests merged in 2020-10, with the labels that each got.

#43 Add dark mode support
  package.json
  public/index.html
  src/App.scss
  src/App.tsx
  src/index.tsx
  src/react/Navbar.tsx
  src/react/Timer.tsx
  src/react/components/Home.tsx
  src/react/components/Recipe/Recipe.tsx
  src/react/components/RecipeForm.tsx
Labels: size/M

#44 Update recipes.json
  src/main/resources/recipes.json
Labels: size/S

#47 Add props files for heroku
  .gitignore
  src/main/resources/application-prod.yml
  src/main/resources/application-sample.yml
  src/main/resources/application.yml
Labels: size/M

#48 Keep cards same size
  src/App.scss
  src/react/app/Home/Home.tsx
  src/react/app/Home/components/RecipeCard.tsx
  src/react/app/Home/components/RecipeGrid.tsx
Labels: size/S

#54 Fix Timer
  src/react/app/Recipe/Components/Timer.tsx
Labels: size/M

#62 Eh/move create recipe button
  src/react/components/Navbar/Navbar.tsx
Labels: size/S

#61 Eh/enhance card look
  public/index.html
  src/App.scss
  src/main/resources/recipes.json
  src/react/app/Home/components/RecipeCard.tsx
  src/react/app/Recipe/Recipe.tsx
  src/react/components/Hero.tsx
  src/react/components/Navbar/Navbar.tsx
Labels: size/L

#60 Eh/recipe form columns
  package.json
  public/index.html
  src/App.scss
  src/main/resources/recipes.json
  src/react/app/Home/components/RecipeCard.tsx
  src/react/app/Recipe/Recipe.tsx
  src/react/app/RecipeForm/RecipeForm.tsx
  src/react/components/Hero.tsx
  src/react/components/Navbar/Navbar.tsx
Labels: size/XL

#74 editable timer
  src/react/app/Recipe/Components/Ingredients.tsx
  src/react/app/Recipe/Components/Timer.tsx
  src/react/app/Recipe/Recipe.tsx
Labels: size/M

#76 fixes #66
  src/react/app/Recipe/Recipe.tsx
Labels: size/XS
