Repository hicks-team/RecipeBook, pull requests merged in 2020-12, with the labels that each got.

#77 big changes for MyAccount page, working but still in progress
  package.json
  src/App.tsx
  src/react/app/MyAccount/MyAccount.tsx
  src/react/app/MyAccount/components/MyAccountComponent.tsx
  src/react/app/MyAccount/components/SmallRecipeCard.tsx
  src/react/app/RecipeForm/Components/EmojiSelector.tsx
  src/react/app/RecipeForm/RecipeForm.tsx
  src/react/hooks/useIsMobile.tsx
  src/react/types/types.ts
Labels: size/L

#80 Click on direction to toggle 'isDone' status
  src/react/app/Recipe/Components/Direction.tsx
Labels: size/S

#79 global user context
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  public/favicon/favicon-dark.png
  public/favicon/favicon.png
  src/App.tsx
  src/react/app/Home/components/RecipePicker.tsx
  src/react/app/MyAccount/MyAccount.tsx
  src/react/app/Recipe/Components/Direction.tsx
  src/react/app/Recipe/Recipe.tsx
  src/react/app/RecipeForm/Components/EmojiSelector.tsx
  src/react/app/RecipeForm/RecipeForm.tsx
  src/react/authFetch.ts
  src/react/components/Navbar/Navbar.tsx
  src/react/components/Navbar/components/LoginForm.tsx
  src/react/components/Navbar/components/SignUpForm.tsx
  src/react/components/Navbar/components/UserAccess.tsx
  src/react/components/UserContext.tsx
  tsconfig.json
Labels: size/L

#83 Simplify userfavorites
  src/App.tsx
  src/react/UserContext.tsx
  src/react/app/Home/components/RecipeCard.tsx
  src/react/app/Recipe/Components/Direction.tsx
  src/react/app/RecipeForm/Components/EmojiSelector.tsx
  src/react/app/RecipeForm/RecipeForm.tsx
  src/react/components/FavoriteButton.tsx
  src/react/components/Navbar/Navbar.tsx
  src/react/components/Navbar/components/UserAccess.tsx
Labels: size/L

#87 Recipe form validation
  package-lock.json
  package.json
  src/react/app/RecipeForm/Components/FormikInput.tsx
  src/react/app/RecipeForm/RecipeForm.tsx
  src/react/app/RecipeForm/constants.tsx
Labels: size/XL
