Repository hicks-team/RecipeBook, pull requests merged in 2022-10, with the labels that each got.

#113 Server2
  .idea/.gitignore
  README.md
  frontend/README.md
  frontend/package.json
  frontend/src/app/RecipeForm/RecipeForm.tsx
  frontend/src/app/RecipeForm/constants.tsx
  frontend/src/helpers/apiUrl.ts
  frontend/src/helpers/authFetch.ts
  frontend/src/types/types.ts
  server/.eslintignore
  server/.eslintrc.json
  server/.gitignore
  server/.prettierignore
  server/.prettierrc.json
  server/Dockerfile
  server/README.md
  server/config/logger.ts
  server/docker-compose.yml
  server/fly.toml
  server/index.ts
  server/jest.config.ts
  server/package-lock.json
  server/package.json
  server/src/config/logger.ts
  server/src/index.ts
  server/src/prisma/schema.prisma
  server/src/prismaClient.ts
  server/src/recipeService.ts
  server/src/routes/apiSchema.ts
  server/src/routes/recipeRoutes.ts
  server/src/utils.ts
  server/tsconfig.json
Labels: size/XXL

#114 updating readmes with correct information
  frontend/README.md
  server/README.md
Labels: size/XS

#115 fix fe build
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AuthDialog.tsx
  frontend/src/hooks/useUser.ts
  frontend/src/index.tsx
  server/package-lock.json
Labels: size/M

#118 add notes to be readme
  server/README.md
Labels: size/M

#117 Update recipes.json
  server/recipes.json
Labels: size/M

#116 fix auth deps
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AuthDialog.tsx
Labels: size/XS

#119 a little more logging, removing pointless console logging, fixing som…
  server/src/index.ts
  server/src/recipeService.ts
  server/src/routes/recipeRoutes.ts
  server/src/utils.ts
Labels: size/S

#120 Update recipes.json
  server/recipes.json
Labels: size/S

#122 Update recipes.json
  server/recipes.json
Labels: size/M

#123 rename server -> backend
  backend/.eslintignore
  backend/.eslintrc.json
  backend/.gitignore
  backend/.prettierignore
  backend/.prettierrc.json
  backend/Dockerfile
  backend/README.md
  backend/docker-compose.yml
  backend/fly.toml
  backend/jest.config.ts
  backend/package-lock.json
  backend/package.json
  backend/recipes.json
  backend/src/config/logger.ts
  backend/src/index.ts
  backend/src/prisma/schema.prisma
  backend/src/prismaClient.ts
  backend/src/recipeService.ts
  backend/src/routes/apiSchema.ts
  backend/src/routes/recipeRoutes.ts
  backend/src/utils.ts
  backend/tsconfig.json
Labels: size/XS
